### ISSUE TITLE
Default build fails for softfp arm platforms

### ISSUE THREAD

**Issue by wak-google** [libjpeg-turbo/libjpeg-turbo#523]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No

**Clear and concise description of the bug:**
If you target an armv7-a or armv6 core that only has softfp available it will try to compile the SIMD intrinsics and fail, even without the REQUIRES_SIMD flag set.

**Expected behavior:**
Disables SIMD builds automatically or add the correct compiler flags to generate the code and detect at runtime if it can be used.

**Observed behavior:**

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
gcc 11.1, yocto/poky master

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
2.1.0

**Additional information:**
```
-- The C compiler identification is GNU 11.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot-native/usr/bin/arm-openbmc-linux-gnueabi/arm-openbmc-linux-gnueabi-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_BUILD_TYPE = Release
-- VERSION = 2.1.0, BUILD = 20210528
-- 32-bit build (arm)
-- CMAKE_INSTALL_PREFIX = /usr
-- CMAKE_INSTALL_BINDIR = bin (/usr/bin)
-- CMAKE_INSTALL_DATAROOTDIR = share (/usr/share)
-- CMAKE_INSTALL_DOCDIR = share/doc/libjpeg-turbo (/usr/share/doc/libjpeg-turbo)
-- CMAKE_INSTALL_INCLUDEDIR = include (/usr/include)
-- CMAKE_INSTALL_LIBDIR = lib (/usr/lib)
-- CMAKE_INSTALL_MANDIR = share/man (/usr/share/man)
-- Shared libraries enabled (ENABLE_SHARED = 1)
-- Static libraries disabled (ENABLE_STATIC = 0)
-- 12-bit JPEG support disabled (WITH_12BIT = 0)
-- Arithmetic decoding support enabled (WITH_ARITH_DEC = 1)
-- Arithmetic encoding support enabled (WITH_ARITH_ENC = 1)
-- TurboJPEG API library enabled (WITH_TURBOJPEG = 1)
-- TurboJPEG Java wrapper disabled (WITH_JAVA = 0)
-- In-memory source/destination managers enabled (WITH_MEM_SRCDST = 1)
-- Emulating libjpeg API/ABI v6.2 (WITH_JPEG7 = 0, WITH_JPEG8 = 0)
-- libjpeg API shared library version = 62.3.0
-- Compiler flags =  -march=armv7-a -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0=/usr/src/debug/libjpeg-turbo/1_2.1.0-r0                      -fdebug-prefix-map=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0=/usr/src/debug/libjpeg-turbo/1_2.1.0-r0                      -fdebug-prefix-map=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot=                      -fdebug-prefix-map=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot-native=   -march=armv7-a -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot -DNDEBUG
-- Linker flags = -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,-z,relro,-z,now 
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Performing Test HAVE_BUILTIN_CTZL
-- Performing Test HAVE_BUILTIN_CTZL - Success
-- Looking for include file locale.h
-- Looking for include file locale.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for memset
-- Looking for memset - found
-- Looking for memcpy
-- Looking for memcpy - found
-- Check size of unsigned char
-- Check size of unsigned char - done
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Performing Test INCOMPLETE_TYPES
-- Performing Test INCOMPLETE_TYPES - Success
-- Compiler supports pointers to undefined structures.
-- Performing Test INLINE_WORKS
-- Performing Test INLINE_WORKS - Success
-- INLINE = __inline__ __attribute__((always_inline)) (FORCE_INLINE = 1)
-- Performing Test HAVE_THREAD_LOCAL
-- Performing Test HAVE_THREAD_LOCAL - Success
-- THREAD_LOCAL = __thread
-- Performing Test HAVE_VERSION_SCRIPT
-- Performing Test HAVE_VERSION_SCRIPT - Success
-- Linker supports GNU-style version scripts
-- CMAKE_EXECUTABLE_SUFFIX = 
-- Looking for vld1_s16_x3
-- Looking for vld1_s16_x3 - not found
-- Looking for vld1_u16_x2
-- Looking for vld1_u16_x2 - not found
-- Looking for vld1q_u8_x4
-- Looking for vld1q_u8_x4 - not found
-- Use partial Neon SIMD intrinsics implementation (NEON_INTRINSICS = OFF)
-- The ASM compiler identification is GNU
-- Found assembler: /build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot-native/usr/bin/arm-openbmc-linux-gnueabi/arm-openbmc-linux-gnueabi-gcc
-- CMAKE_ASM_FLAGS =  -march=armv7-a -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0=/usr/src/debug/libjpeg-turbo/1_2.1.0-r0                      -fdebug-prefix-map=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0=/usr/src/debug/libjpeg-turbo/1_2.1.0-r0                      -fdebug-prefix-map=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot=                      -fdebug-prefix-map=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot-native=   -march=armv7-a -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot  -march=armv7-a -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0=/usr/src/debug/libjpeg-turbo/1_2.1.0-r0                      -fdebug-prefix-map=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0=/usr/src/debug/libjpeg-turbo/1_2.1.0-r0                      -fdebug-prefix-map=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot=                      -fdebug-prefix-map=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot-native=   -march=armv7-a -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot -DNDEBUG
-- SIMD extensions: arm (WITH_SIMD = 1)
-- FLOATTEST = no-fp-contract
-- Performing Test HAVE_HARD_FLOAT
-- Performing Test HAVE_HARD_FLOAT - Failed
-- RPM architecture = armel, DEB architecture = armel
-- Configuring done
-- Generating done
```

```
/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot-native/usr/bin/arm-openbmc-linux-gnueabi/arm-openbmc-linux-gnueabi-gcc  -I. -I/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/libjpeg-turbo-2.1.0 -Isimd/arm -march=armv7-a -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0=/usr/src/debug/libjpeg-turbo/1_2.1.0-r0                      -fdebug-prefix-map=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0=/usr/src/debug/libjpeg-turbo/1_2.1.0-r0                      -fdebug-prefix-map=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot=                      -fdebug-prefix-map=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot-native=   -march=armv7-a -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot -DNDEBUG -fPIC -mfpu=neon -MD -MT simd/CMakeFiles/simd.dir/arm/jcsample-neon.c.o -MF simd/CMakeFiles/simd.dir/arm/jcsample-neon.c.o.d -o simd/CMakeFiles/simd.dir/arm/jcsample-neon.c.o -c /build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/libjpeg-turbo-2.1.0/simd/arm/jcsample-neon.c
In file included from /build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/libjpeg-turbo-2.1.0/simd/arm/jcsample-neon.c:32:
/build/tmp/work/armv7a-openbmc-linux-gnueabi/libjpeg-turbo/1_2.1.0-r0/recipe-sysroot-native/usr/lib/arm-openbmc-linux-gnueabi/gcc/arm-openbmc-linux-gnueabi/11.1.1/include/arm_neon.h:31:2: error: #error "NEON intrinsics not available with the soft-float ABI.  Please use -mfloat-abi=softfp or -mfloat-abi=hard"
   31 | #error "NEON intrinsics not available with the soft-float ABI.  Please use -mfloat-abi=softfp or -mfloat-abi=hard"
```

**Comment by wak-google** [comment]
Comparing this to 2.0.6, it looks like jcsample-neon.c is new or was not previously enabled. And the configure step checking `HAVE_HARD_FLOAT` is also new

**Comment by dcommander** [comment]
The error message literally tells you how to fix the problem, and I have confirmed that doing what it says does indeed fix the problem.

**Comment by dcommander** [comment]
Note that libjpeg-turbo 2.1.0 introduced a complete overhaul of the Neon SIMD extensions, so yes, **jcsample-neon.c** is new.  Arm contributed most of that new code.

**Comment by dcommander** [comment]
To clarify, **arm_neon.h** expects `__ARM_FP` to be defined, which it won't be unless you specify `-mfloat-abi=softfp` or `-mfloat-abi=hard`.  As I'm sure you know, both of those options use hardware floating point instructions, but `softfp` uses a floating point ABI that is backward compatible with non-FPU-equipped systems and applications.  The default compiler setting is `-mfloat-abi=soft` (software floating point), which is incompatible with Neon intrinsics.  That option did work with the GAS code in libjpeg-turbo 2.0.x and prior, but to the best of my understanding, that was because we were forcing the issue by assembling the Neon code rather than compiling it.  If I recall, the resulting libjpeg-turbo binary was not truly compatible with non-FPU-equipped systems unless you disabled the libjpeg-turbo SIMD extensions.  The use of Neon intrinsics makes that a more explicit requirement.

The new `HAVE_HARD_FLOAT` test doesn't affect compilation at all.  It simply determines whether you are building for the hard or soft float ABI and uses that information to correctly specify the package architecture names for DEB and RPM packaging.

**Comment by wak-google** [comment]
I don't understand how this is not a bug. Our systems don't use float-abi=softfp generally for compiling code because they don't have hardware floating point support. We couldn't compile any of our non-runtime detected floating point code this way. Shouldn't libjpeg-turbo's build system accommodate systems that are possibly softfp, and add the required float-abi=softfp flag to code that will only be run at runtime if the system is detected to support the needed intrinsics?

So you are suggesting we have to add flags to detect softfp in the meta build system and add the WITH_SIMD=OFF flag?

**Comment by dcommander** [comment]
I think I see what you’re saying. Ideally, the build system should detect when `-mfloat-abi=soft` (the default) and runtime Neon auto-detection will be used (Linux build without `mfpu=neon` specified.) In that case, it should add `-mfloat-abi=softfp` when building only the SIMD functions, thus allowing those functions to be used if runtime auto-detection detects a Neon-equipped CPU but still allowing the non-SIMD code to work on systems without Neon or an FPU.

That situation was probably an oversight in the redesign of the Neon SIMD extensions, since the major platforms are moving away from AArch32 support and we focused our testing on AArch64. I will investigate how best to make those changes, but please be patient, as it will probably take me a few weeks to get to it.

**Comment by wak-google** [comment]
Yeah, no problem. I'll just earmark the bug and we will hold off on updating until then.

**Comment by dcommander** [comment]
Should work now.  I regression-tested the fix against the expected results from various permutations of compiler options by using the following script on Ubuntu 20.04:
```
set -e
set -u

NUMCPUS=`grep -c '^processor' /proc/cpuinfo`

for COMPILER in gcc clang; do

	for ABI in hard softfp soft; do

		CFLAGS="-mthumb -Wall -Werror -mfloat-abi=$ABI"

		if [ "$COMPILER" = "gcc" -a "$ABI" = "hard" ]; then
			CC=/usr/bin/arm-linux-gnueabihf-gcc-8
			CFLAGS="$CFLAGS -march=armv7-a"
		elif [ "$COMPILER" = "gcc" ]; then
			CC=/usr/bin/arm-linux-gnueabi-gcc-8
			CFLAGS="$CFLAGS -march=armv7"
		elif [ "$ABI" = "hard" ]; then
			CC=/usr/bin/clang-10
			CFLAGS="$CFLAGS -B/usr/arm-linux-gnueabihf/bin -isystem /usr/arm-linux-gnueabihf/include --target=armv7a-linux-gnueabihf -march=armv7-a"
		else
			CC=/usr/bin/clang-10
			CFLAGS="$CFLAGS -B/usr/arm-linux-gnueabi/bin -isystem /usr/arm-linux-gnueabi/include --target=armv7-linux-gnueabi -march=armv7"
		fi

		for FPU in none neon; do

			if [ "$FPU" = "neon" ]; then
				CFLAGS="$CFLAGS -mfpu=neon"
			fi

			echo "###############################################################################"
			echo
			echo COMPILER=$COMPILER ABI=$ABI FPU=$FPU
			echo CC=$CC
			echo CFLAGS=$CFLAGS
			echo

			rm -rf CMake*

			cat <<EOF >linux-arm-toolchain.cmake
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_C_FLAGS "$CFLAGS")
set(CMAKE_C_COMPILER $CC)
EOF

			cmake -G"Unix Makefiles" \
				-DCMAKE_TOOLCHAIN_FILE=linux-arm-toolchain.cmake \
				-DREQUIRE_SIMD=1 -DENABLE_SHARED=0 -DWITH_TURBOJPEG=0 ..

			if [ "$COMPILER" = "clang" ]; then
				grep HAVE_VLD1Q_U8_X4:INTERNAL=1 CMakeCache.txt
				grep HAVE_VLD1_S16_X3:INTERNAL=1 CMakeCache.txt
				grep HAVE_VLD1_U16_X2:INTERNAL=1 CMakeCache.txt
				grep NEON_INTRINSICS:BOOL=ON CMakeCache.txt
			else
				grep -e 'HAVE_VLD1Q_U8_X4:INTERNAL=$' CMakeCache.txt
				grep -e 'HAVE_VLD1_S16_X3:INTERNAL=$' CMakeCache.txt
				grep -e 'HAVE_VLD1_U16_X2:INTERNAL=$' CMakeCache.txt
				grep NEON_INTRINSICS:BOOL=OFF CMakeCache.txt
			fi

			if [ "$ABI" = "soft" ]; then
				grep NEED_SOFTFP_FOR_INTRINSICS:INTERNAL=1 CMakeCache.txt
			elif [ "$ABI" = "softfp" -a "$FPU" = "none" -a "$COMPILER" = "gcc" ]; then
				grep NEED_SOFTFP_FOR_INTRINSICS:INTERNAL=1 CMakeCache.txt
			else
				grep -e 'NEED_SOFTFP_FOR_INTRINSICS:INTERNAL=$' CMakeCache.txt
			fi

			make -j$NUMCPUS --load-average=$NUMCPUS

		done
	done
done

echo
echo GREAT SUCCESS!
```
