### ISSUE TITLE
tjexample.c does not build as C++ with VC++

### ISSUE THREAD

**Issue by randomascii** [libjpeg-turbo/libjpeg-turbo#714]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

Yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

No

**Clear and concise description of the bug:**

When tjexample.c is compile as C++ using VC++ there are several compile errors, fixable with some simple changes. I have a PR that will resolve this ready, assuming that C++ and VC++ compatibility are desirable.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

Create a VC++ project, copy tjexample.cc into the default C++ file, and add libjpeg-turbo as an include directory. Compile.

**Image(s) needed in order to reproduce the bug (if applicable):**

n/a

**Expected behavior:**

Compiling with no errors

**Observed behavior:**

1>C:\src\code\libjpeg_test\libjpeg_test.cpp(277,28): error C2440: '=': cannot convert from 'void *' to 'unsigned char *'
1>C:\src\code\libjpeg_test\libjpeg_test.cpp(277,28): message : Conversion from 'void*' to pointer to non-'void' requires an explicit cast
1>C:\src\code\libjpeg_test\libjpeg_test.cpp(187,10): error C4996: 'strnicmp': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strnicmp. See online help for details.
...
1>C:\src\code\libjpeg_test\libjpeg_test.cpp(206,17): error C4996: 'stricmp': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _stricmp. See online help for details.
...
There are many instances of the strnicmp and stricmp errors.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

Windows 10, VC++ 2022, x64

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

This was reproduced on tip-of-tree, commit ebca79d508d424687707462675a4a5f09ab4429c.

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

The need for the cast was introduced in fc01f467. The errors with strnicmp and stricmp seem to have been around since the beginning.

**Comment by randomascii** [comment]
I created this pull request to resolve this issue. It's pretty straightforward, if VC++/C++ compatibility is a goal for tjexample.c. If not then this issue should be closed as out of scope. Here is the PR:

https://github.com/libjpeg-turbo/libjpeg-turbo/pull/715

**Comment by dcommander** [comment]
**tjexample.c** is an example of TurboJPEG API usage. Since the API is a C API and libjpeg-turbo is a C90 project (C++ is never used except when building our fuzzers), the example is written in C. If it was intended to be compiled as C++, then it would have been given a C++ extension. 
Our CI system checks for C90 conformance and other C compiler warnings (including pedantic ones) in order to ensure that our C code is as clean as possible, but again, we are not a C++ project. The goal is that the public libjpeg and TurboJPEG APIs should be usable from C++ projects but not that any part of the libjpeg-turbo code base should be cleanly buildable with a C++ compiler. C++ compilers are used to build C++ code, not C code.
