### PR TITLE
(Turbojpeg): Fix linking when C_PROGRESSIVE_SUPPORTED is undefined

### PR DESCRIPTION
**Pull request by fsbruva**
This fixes a latent regression introduced in 0713c1b and aba6ae5. 

**Description of bug:** Final linking fails when jmorecfg.h undefines C_PROGRESSIVE_SUPPORTED.

**Affected versions:** 1.3.90+

**Step to reproduce:**
1. clone repo
2. Edit jmorecfg.h to #undef C_PROGRESSIVE_SUPPORTED
3. Run cmake
4. Run make

**Resulting error:**
`[ 88%] Building C object CMakeFiles/tjbench-static.dir/tjutil.c.o
[ 89%] Linking C executable tjbench-static
libturbojpeg.a(turbojpeg.c.o): In function `setCompDefaults':
turbojpeg.c:(.text+0x364): undefined reference to `jpeg_simple_progression'
libturbojpeg.a(turbojpeg.c.o): In function `tjTransform':
turbojpeg.c:(.text+0xa163): undefined reference to `jpeg_simple_progression'
collect2: error: ld returned 1 exit status
CMakeFiles/tjbench-static.dir/build.make:121: recipe for target 'tjbench-static' failed
make[2]: *** [tjbench-static] Error 1
CMakeFiles/Makefile2:205: recipe for target 'CMakeFiles/tjbench-static.dir/all' failed
make[1]: *** [CMakeFiles/tjbench-static.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2`

**Observed on:** See [my intentionally failed builds](https://travis-ci.com/fsbruva/libjpeg-turbo/builds/141020993)
Ubuntu 16.05 AMD64, ppc, arm & s390x (clang and gcc)
Ubuntu 18.04 AMD64 (clang and gcc) 
Ubuntu 14.04 AMD64 (clang and gcc)
macOS 10.11, 10.12, 10.13, 10.14
FreeBSD 11.2-RELEASE AMD64 (clang)

**Proposed fix:** Add preprocessor conditional for the 3 uses of jpeg_simple_progression within turbjpeg.c.

**Explanation:** Within jcparam.c, the code for function jpeg_simple_progression() is conditionally compiled based on the C_PROGRESSIVE_SUPPORTED preprocessor variable being defined at [L405](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/52291467e1d24ed5c99186b93722e740902bd19c/jcparam.c#L405-L468) However, within turbojpeg.c, no such check exists, causing final linking to fail when jmorecfg.h undefines C_PROGRESSIVE_SUPPORTED.

### CODE REVIEW

**Comment by dcommander** [comment]
Why do you need to build libjpeg-turbo without `C_PROGRESSIVE_SUPPORTED` defined?  Please understand that the original libjpeg library, by virtue of having been created in the early 1990s, had constraints that we no longer have.  It had to work on highly-resource-constrained systems (including 640k MS-DOS systems), which is why it was originally possible to disable some features by adjusting the #defines in jmorecfg.h.  Because those #defines are in a public header, they are part of the public libjpeg API, but the TurboJPEG API has never supported them-- except in cases where doing so conferred some sort of tangible benefit (for instance, TurboJPEG can be built with `-DNO_GETENV -DNO_PUTENV`, because those functions are disallowed in programs that will be posted to the Microsoft app store.)  The TurboJPEG API, by virtue of being a whole-image API, is not designed to save memory.  If memory is truly constrained, then a programmer should use the libjpeg API with buffered I/O.  Much more memory can be saved in that manner than by disabling `C_PROGRESSIVE_SUPPORTED`, so unless I'm missing something, there is no compelling argument to support disabling `C_PROGRESSIVE_SUPPORTED` in the TurboJPEG API.  The libjpeg API library builds just fine without `C_PROGRESSIVE_SUPPORTED`, so those desiring to disable progressive encoding should disable TurboJPEG as well.  Just understand that those sorts of builds are legacy, meaning that I only feel compelled to support them if libjpeg-turbo-specific features (including the TurboJPEG API) are not in use.  I am open to being convinced otherwise, but I am not open to supporting a long-deprecated feature unless there's a good reason to do so.

**Comment by dcommander** [comment]
@fsbruva Please answer the question I posed above:  is there a good reason why you need to build libjpeg-turbo without `C_PROGRESSIVE_SUPPORTED` defined?

**Comment by fsbruva** [comment]
No - there is no good reason :-), other than "inertia."

I inherited a project that used an archaic version of libjpeg-turbo, but with a customized jmorecfg.h. The project itself uses the libjpeg API, so the proper action is for me to disable the libjpeg-turbo API, or stop using the customized jmorecfg.h.

Please accept my apologies for bothering you with this noise, my deep gratitude for your thorough reply, and I'll close this.

**Comment by dcommander** [comment]
No problem.  I just wanted to understand the issue.  If there were a valid reason for disabling `C_PROGRESSIVE_SUPPORTED`, then the right way to go about it would have been to add a new CMake option and a build-time-generated jmorecfg.h file.

**Comment by fsbruva** [comment]
Understood. The downstream project (libmediascan) doesn't actually have a preference on the contents of jmorecfg.h. But, the primary downstream project that uses libmediascan (slimserver-vendor), uses a heavily customized jmorecfg.h to reduce both library size and memory use. It `#undef`'s at total of 8 preprocessor variables.

I understand what you mean about using the build system (CMake) options as the right answer, generally. Correct me if I'm wrong, but given the number of variables (15 by my count - ignoring the RGB macros), adding the additional CMake options seems to have limited utility. Or, would you like to see them all added so that build options (custom jmorecfg.h) aren't bypassing the build system?

**Comment by dcommander** [comment]
I am not interested in making any modifications to libjpeg-turbo unless they are broadly applicable.  We don't support customized jmorecfg.h files.  I just meant that *if* there were sufficient justification for disabling `C_PROGRESSIVE_SUPPORTED`, then the correct way to do so would be to create a new CMake option.  However, given that there is not sufficient justification for disabling `C_PROGRESSIVE_SUPPORTED`, it's a moot point.  If the downstream project doesn't use the TurboJPEG API, then simply disable the TurboJPEG API in the custom build.

**Comment by fsbruva** [comment]
Good copy. Roger on all.
