### ISSUE TITLE
Broken build due to missing -lm

### ISSUE THREAD

**Issue by bkuhls** [libjpeg-turbo/libjpeg-turbo#907]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
no

**Clear and concise description of the bug:**
https://github.com/libjpeg-turbo/libjpeg-turbo/commit/ed00e0f4b39291e954958b96a8d941ca4a9e03a2 removed the dependency to libm which causes build errors detected by the buildroot autobuilders on [i686](https://autobuild.buildroot.net/?reason=jpeg-turbo%&arch=i686):
https://autobuild.buildroot.net/results/981/98114d4ea7afe62bb4cef934a06bf289d863ad3f/
```
[ 43%] Linking C executable tjunittest
/home/autobuild/autobuild/instance-43/output-1/per-package/jpeg-turbo/host/bin/../lib/gcc/i686-buildroot-linux-gnu/15.3.0/../../../../i686-buildroot-linux-gnu/bin/ld: libturbojpeg.so.0.5.0: undefined reference to `__fpclassifyf'
```

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
Build the package on i686.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
Linux/i686/glibc

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

**Comment by dcommander** [comment]
You obviously did not check existing issues. This is a dupe and has already been fixed.
