### ISSUE TITLE
Regression to static builds using libjpeg-turbo

### ISSUE THREAD

**Issue by ypnos** [libjpeg-turbo/libjpeg-turbo#341]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?** Y

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?** N

**Clear and concise description of the bug:**

Statically linking against libjpeg-turbo fails with linker errors given below.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

Compile libjpeg-turbo according to [1]:
```
x86_64-w64-mingw32-cmake -DWITH_JPEG8=ON .. && make
```
Try to compile and link any other software that statically links libjpeg-turbo, e.g. [2]

**Expected behavior:**

The linker succeds.

**Observed behavior:**

Statically linking against libjpeg-turbo 2.0.2 fails with
```
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libjpeg.a(jcapistd.c.obj):(.text+0x156): undefined reference to `__stack_chk_fail'
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libjpeg.a(jcapistd.c.obj):(.rdata$.refptr.__stack_chk_guard[.refptr.__stack_chk_guard]+0x0): undefined reference to `__stack_chk_guard'
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libjpeg.a(jcmarker.c.obj):(.text+0x209b): undefined reference to `__stack_chk_fail'
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libjpeg.a(jcmaster.c.obj):(.text+0x705): undefined reference to `__stack_chk_fail'
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libjpeg.a(jcphuff.c.obj):(.text+0xb50): undefined reference to `__stack_chk_fail'
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libjpeg.a(jcphuff.c.obj):(.text+0x1142): undefined reference to `__stack_chk_fail'
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libjpeg.a(jcphuff.c.obj):(.text+0x1889): undefined reference to `__stack_chk_fail'
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libjpeg.a(jdapistd.c.obj):(.text+0x287): more undefined references to `__stack_chk_fail' follow
```

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

Arch Linux, mingw-w64-gcc version 8.2.0, cmake version 3.13.4.

**libjpeg-turbo version(s) in which the bug was observed:** 2.0.2

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):** after 2.0.1

**Additional information:**

A workaround is to add `-lssp` to the linker arguments.

[1]: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mingw-w64-libjpeg-turbo
[2]: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mingw-w64-qt5-base-static

**Comment by Martchus** [comment]
Maybe you've been using the version of the CMake wrapper which had `-fstack-protector-strong` enabled? Recompiling the library with that [change reverted](https://aur.archlinux.org/cgit/aur.git/commit/?h=mingw-w64-cmake&id=b248433ab034926807175f71be9d449a229998b2) would also fix the problem.

If it is really just because of `-fstack-protector-strong` I'm not sure whether this problem should be addressed upstream. We should rather decide whether we want `-fstack-protector-strong` or not. If we want it we should also add `-lssp` [to the CMake wrapper](https://aur.archlinux.org/cgit/aur.git/tree/mingw-cmake.sh?h=mingw-w64-cmake#n13) if that is required for `-fstack-protector-strong`.

**Comment by ypnos** [comment]
Thank you for joining the discussion @Martchus. I tried to find what changed in the sources of libjpeg-turbo that could have caused this problem to no avail. I didn't realize that the cmake wrapper had changed as well. I now assume the cmake wrapper is responsible for this problem.

As to which parameters are best for the cmake wrapper, I do not feel competent to comment.

**Comment by Martchus** [comment]
I've just noticed that the CMake wrapper as provided by my repository also still adds `-fstack-protector-strong`. So I've just updated it to the reverted version until we know how to deal with that flag in case we actually want it.

It also seems like the latest version of `mingw-w64-libjpeg-turbo` in my repo was built with `-fstack-protector-strong`. I better rebuild this without that flag, too.

**Comment by ypnos** [comment]
Thank you. The packages in your repo work as expected. Sorry @dcommander for the bug report in the wrong place.

**Comment by dcommander** [comment]
No problem.  My favorite bugs are the ones that solve themselves.
