### ISSUE TITLE
Replacing standard libjpeg.a with the turbo libjpeg.a gives link error

### ISSUE THREAD

**Issue by MikeCowlishaw** [libjpeg-turbo/libjpeg-turbo#382]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

**Clear and concise description of the bug:**

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

**Image(s) needed in order to reproduce the bug (if applicable):**

**Expected behavior:**

**Observed behavior:**

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the master branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

**Comment by MikeCowlishaw** [comment]
Hi, thanks to earlier reply I now have 32-bit and 64-bit libjpeg.a for Windows (mingw, Win-Builds).

On replacing the 'standard' 32-bit (or 64-bit) version with the 'turbo' library I get "undefined reference to '_imp____acrt_iob_func'" error message during link.

Any ideas on how to fix?

Thanks!

**Comment by dcommander** [comment]
It appears you’re running into a problem similar to this one
https://github.com/msys2/MINGW-packages/issues/3531
which is apparently due to a mismatch in MinGW compiler versions. Which version specifically are you using in your build?

**Comment by MikeCowlishaw** [comment]
Thanks for the quick reply!  That does sound as though it is the same problem.  Here is the gcc -v output for my setup:

m:\programs\pangazer}gcc -v
Reading specs from c:/win-builds/bin/../lib/gcc/i686-w64-mingw32/4.8.3/specs
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=c:/win-builds/bin/../libexec/gcc/i686-w64-mingw32/4.8.3/lto-
wrapper.exe
Target: i686-w64-mingw32
Configured with: ../gcc-4.8.3/configure --prefix=/opt/windows_32 --with-sysroot=
/opt/windows_32 --libdir=/opt/windows_32/lib --mandir=/opt/windows_32/man --info
dir=/opt/windows_32/info --enable-shared --disable-bootstrap --disable-multilib
--with-arch=pentium3 --enable-threads=posix --enable-languages=c,c++ --enable-ch
ecking=release --enable-libgomp --with-system-zlib --with-python-dir=/lib/python
2.7/site-packages --disable-libunwind-exceptions --enable-__cxa_atexit --enable-
libssp --with-gnu-ld --verbose --enable-java-home --with-java-home=/opt/windows_
32/lib/jvm/jre --with-jvm-root-dir=/opt/windows_32/lib/jvm --with-jvm-jar-dir=/o
pt/windows_32/lib/jvm/jvm-exports --with-arch-directory=amd64 --with-antlr-jar='
/home/adrien/projects/win-builds-1.5/slackware64-current/d/gcc/antlr-*.jar' --di
sable-java-awt --disable-gtktest --build=x86_64-slackware-linux --host=i686-w64-
mingw32 --target=i686-w64-mingw32
Thread model: posix
gcc version 4.8.3 (GCC)

**Comment by MikeCowlishaw** [comment]
I just ran yypkg-1.5.0.exe on my Win-builds; it reports all packages are up-to-date (both 32-bit and 64-bit).    So I am a bit stuck, here.  It seems that libjpeg-turbo has this dependency that libjpeg does not?

**Comment by dcommander** [comment]
Where exactly are you getting libjpeg for MinGW?  The IJG does not provide any official binaries, so any MinGW binary of that code base is being provided by someone else.

**Comment by MikeCowlishaw** [comment]
I build my libjpeg from the source (currently  JVERSION  "9b  17-Jan-2016"); it compiles without Warnings and links cleanly (and works).  However it took a fair bit of work to get it to that state and build both 32- and 64-bit libraries.  I was hoping to avoid that by using the libjpeg-turbo .a files.

**Comment by dcommander** [comment]
Ah, well, that’s why libjpeg doesn’t have the dependency— because you are building it using the same compiler. I suspect that the dependency comes in because libjpeg-turbo is being built with a newer GCC version. I need to look into that. If there’s a way to work around the issue, I would certainly like to do so.

**Comment by MikeCowlishaw** [comment]
Makes sense.

A work-around would be much appreciated (maybe even a dummy reference elsewhere in my code, or is it a real routine that libjpeg-turbo uses?)!   I've already put the instrumentation into PanGazer so I can time the difference(s) :-).    [I was shocked to discover that using libjpeg is (slightly) slower than using the Windows GDI with all the baggage that comes with that.  Both are very slow for loading large images.]

**Comment by dcommander** [comment]
No, it isn't a function libjpeg-turbo uses.  Please read the link I posted above, which explains that it's an internal function that is automatically included by later MinGW GCC versions in order to support Microsoft's ucrt (Universal CRT) library.  I am very busy, and this work has to be paid for with our general fund, so it is not high-priority.  Please be patient.  Every question I have to answer delays the resolution of this issue.

**Comment by MikeCowlishaw** [comment]
Hi dcommander (and no this is not a question :-)).  I did read that link and a number of others but they all seemed speculative or opinionated -- unlike your to-the-point replies.

I wasn't aware that this was paid-for work (my intended use of libjpeg-turbo is neither work nor paid-for, nor is it commercial in any sense) but I would be happy to make a donation to the 'general fund' (where is that?) if that would help.   To save time (and avoid the dreaded questionmark) I will donate €100 to the fund right now, if you indicate where that is.   More later, when issue resolved -- I really like the idea and principle of libjpeg-turbo!

Mike

**Comment by dcommander** [comment]
Yes, I am an independent developer, so I maintain this and a few other open source projects for a living.  Donations are always very much appreciated, since those are directly translated into hours spent developing and maintaining this code base.  There is a donation link at libjpeg-turbo.org.

**Comment by MikeCowlishaw** [comment]
AhSo .. one learns something new every day; I had no idea that a living could be made from open-source projects.  Good to hear that's possible!

Donation duly made as promised ($ rather than € as that what site wanted, but close-enough).

**Comment by dcommander** [comment]
Not a good living, but I've managed to avoid starvation for 10 years by attracting corporate patronage and NGO research grants in order to fund large feature development on the projects.  It is likely the only reason why the projects I maintain (including this one) have managed to move forward as much as they have, because few corporate employers would allow me to focus this much on these open source projects-- at least not with the level of vendor neutrality that I have maintained.

**Comment by dcommander** [comment]
However, I also don't know of anyone else in the open source community that has managed to carve out a living like this.  Most of my income comes from high-speed open source enterprise remote 3D display software that has a unique niche.  The companies that are deploying it have saved millions in equipment refreshes and ongoing IT costs, so paying me thousands a year is pretty easy to justify.  It's a lot harder to monetize my work on libjpeg-turbo, and the general fund that Cendio AB provides as of this year, as well as some recent funded development contracts, is a big reason why I've managed to keep it going.  I've pontificated in the past how the open source community really needs its own app store, since much of our code (anything with a LGPL or GPL license) isn't allowed on the Windows or Apple app stores.  Then we could charge a small fee in order to get access to our official binaries, and the OSS app store mechanism would provide a cross-platform means for users to keep those binaries up to date.  BinTray has something that sort of resembles this, but I haven't had a chance to look into it.

**Comment by MikeCowlishaw** [comment]
Interesting!  Explains a lot.

On App stores .. I suppose I'd prefer one big 'Internet' app store, that had all the apps for all the operating systems.   No tying-in to a particular 'eco-system'.   A pipe dream of course :-(

From your posting times, I suspect you are somewhere in Europe.

**Comment by dcommander** [comment]
The issue has been reproduced.  It is specific to the static library, so while I'm figuring out a fix, you can link against libjpeg.dll.a instead, which works.

**Comment by MikeCowlishaw** [comment]
Hmm, I haven't used DLLs for a couple of decades ...

**Comment by MikeCowlishaw** [comment]
Will wait.

**Comment by dcommander** [comment]
New builds of the libjpeg-turbo SDK for MinGW have been uploaded to https://sourceforge.net/projects/libjpeg-turbo/files/2.0.3, and those new builds should fix this issue.  It took some effort, but it was the right thing to do.  I switched our official builds to a fixed installation of GCC 6.4.0 from MinGW-builds, so they won't be affected by MSYS2 updates on my build system.  That was why I didn't notice this problem.  When I initially switched to MSYS2, it was using GCC 5 and then GCC 6.  Apparently it started using GCC 7 at some point before the release of libjpeg-turbo 2.0.1, which was the first release to exhibit this backward compatibility issue.

**Comment by MikeCowlishaw** [comment]
Sounds excellent!!   Many thanks!

I just hit a snag when trying the new .exes, however.  On trying to install the new version I got a message to uninstall first, which I did.   Both uninstalls reported an error (unspecified), but after the uninstall there was no trace of the files on the C: disk so it seemed to have worked.  I also did a simple search of the registry and found no mention of 'turbo'.   But when I ran the .exes again I still get the 'please uninstall' popup (screenshot attached).    Any ideas?

 
![pic298](https://user-images.githubusercontent.com/56477819/67487430-d2c89000-f665-11e9-877d-36141b707be5.jpg)

**Comment by dcommander** [comment]
Can't reproduce, but apparently the old installer didn't delete **c:\windows\system32\libturbojpeg.dll** for some reason.  Delete that file manually and try again.

**Comment by MikeCowlishaw** [comment]
That file did indeed exist, deleted it and 32-bit installed normally; thanks!   I'm out of time to test it today, but did try install 64-bit .. get the same message as before, for that.   Is there a similar 64-bit file that has to be deleted?   I did a search of my C: drive for anything with 'turbo' in the name but didn't see anything obvious.   There's copy of the DLL in c:\Windows\SysWOW64 .. is that the problem?

**Comment by MikeCowlishaw** [comment]
Ah .. on a hunch, I deleted the .dll that the 32-bit installed.   The 64-bit then installed so I now have the two libjpeg-turbo-gcc64 and libjpeg-turbo-gcc directories on my C: drive.   I will try the libs tomorrow!  Many thanks for your help so far!

**Comment by MikeCowlishaw** [comment]
I'm delighted to report that everything now works -- and the time to load JPG from file is half the time that it was; a two-times speedup is very significant and very noticeable!

This was really worthwhile; very many thanks for your help!!

I've attached comparative timings for my primary test images (USEGDI=1 is using MS API; if =0 then using original libjpeg or turbo) in case of interest.

Again, many, many thanks.
Mike


[PanGazer-turbo-timings.txt](https://github.com/libjpeg-turbo/libjpeg-turbo/files/3772506/PanGazer-turbo-timings.txt)

**Comment by dcommander** [comment]
If you're decompressing into a 32-bit (RGBX/BGRX/etc.) buffer, you can get even better performance by taking advantage of libjpeg-turbo's colorspace extensions (which aren't supported in libjpeg.)  Also, of course the I/O time (the time spent actually loading the file is a fixed performance cost, not affected by accelerating the JPEG library.

Glad you were able to make it work.

**Comment by MikeCowlishaw** [comment]
I decompress to TRGB (transparency/R/G/B) but easy enough to re-jig from most others.   Colorspace extensions sound very interesting, though -- one advantage of the GDI is that ICC information in the file seems to be handled.     Attached is my 'bête noire' ... GDI shows nice blue skies but loading just with libjpeg  the sky (and shadows) are purple.   Can libjpeg-turbo handle that?  That would be really interesting ...

![PuntaDellaCroce 8500](https://user-images.githubusercontent.com/56477819/67589439-58c10580-f750-11e9-87bc-7e8eb1f6eed8.jpg)

**Comment by dcommander** [comment]
There are additional functions in libjpeg-turbo for handling ICC profiles.  `jpeg_read_icc_profile()` should do what you need.  I'm not sure about the sky color.  Can you post an uncompressed example of the correct color (generated by the GDI) and the incorrect color (generated by the libjpeg API)?

**Comment by dcommander** [comment]
libjpeg-turbo can definitely handle TRGB, though.  The colorspace extensions would call that ARGB (if in fact you intend the transparent component to be first in memory order, i.e. in the right-most byte of the DWORD on little endian machines.)  The A component is set to opaque at the moment (referring to #232, we don't yet support JPEG XT images that embed transparent information into the JPEG image itself, but those are not common.)

**Comment by MikeCowlishaw** [comment]
Re TRGB .. not a problem.  It's my internal format, and not endian.  T byte is transparency (0=opaque) (255-A).  This has the advantage that images loaded with just RGB automatically have 0 in the top byte.  But it's trivial and very fast to reorder or 'flip' the T.  I just find it easier to ignore the T byte when it is 0.

**Comment by MikeCowlishaw** [comment]
Re: jpeg_read_icc_profile() should do what you need. I'm not sure about the sky color.
I thought my copy before was the plain JPG .. if not, I can put it on my website for you to download 'as-is'.   But attached here are three screenshots as presented in three cases:

  -FSP .. as displayed by FSP_Viewer (author is the source of the image)
  -WinGDI .. as loaded using Win GDI and displayed using my PanGazer (with no colour adjustments by me)
  -turbo ... as loaded by libjeg or libjpeg-turbo  and displayed using my PanGazer (with no colour adjustments by me)

The first two look about right (but GDI probably over-saturates); the third is rather purple?

Mike
  
![pic300-turbo](https://user-images.githubusercontent.com/56477819/67594952-692bad00-f75d-11e9-9687-bbab3c540799.jpg)

![pic301WinGDI](https://user-images.githubusercontent.com/56477819/67594883-35e91e00-f75d-11e9-90c7-e1e164c4fd38.jpg)

![pic299-FSP](https://user-images.githubusercontent.com/56477819/67594782-01756200-f75d-11e9-855b-9669c528ee93.jpg)

**Comment by MikeCowlishaw** [comment]
<sigh> images above are in reverse order to my description;  the bottom one is FSP-Viewer, the middle one is PanGazer using Windows GDI, and the top one is PanGazer using libjpeg[-turbo].  The purple cast is much worse when seen 'in real life' .. github may be applying some 'correction'?

**Comment by dcommander** [comment]
If Windows GDI is applying color matching based on an embedded ICC profile in the image, then that could definitely be the difference. Try extracting the profile using `jpeg_read_icc_profile()` and then using LittleCMS (lcms) or the Win32 API (https://docs.microsoft.com/en-us/previous-versions/windows/desktop/wcs/basic-color-management-concepts) to color correct the image based on the profile.

**Comment by MikeCowlishaw** [comment]
Yes -- the screenshots as presented above don't really show the dramatic differences between the three (if interested, happy to package them into a .zip for you).   FSP-Viewer uses littleCMS, Windows GDI does something similar -- but not the same -- and of course plain JPEG read makes no change to the original (very purple) colours.

One day I should do the work and process the ICC myself (I have worked in colour science for decades, e.g, http://speleotrove.com/misc/cowlishaw1985-fundamental.pdf) .. but for now, rather than add another package, I think I'll just check if there's an ICC profile in the Exif, and if so just punt to GDI.  I've only come across the one picture with ICC and if that's slower to load, so be it :-).
