### ISSUE TITLE
i686-w64-mingw32 no longer compiles in v3.1.90 and v3.2.0,

### ISSUE THREAD

**Issue by mywave82** [libjpeg-turbo/libjpeg-turbo#908]
```sh
cat <<EOF > toolchain.cmake
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR X86)
set(CMAKE_C_COMPILER /usr/bin/i686-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER /usr/bin/i686-w64-mingw32-g++)
set(CMAKE_RC_COMPILER /usr/bin/i686-w64-mingw32-windres)
EOF

mkdir -p build
cd build
cmake -G"Unix Makefiles" \
      -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake \
      -DCMAKE_INSTALL_PREFIX=$prefix \
      -DCMAKE_INCLUDE_PATH=$prefix/include \
      -DBUILD_SHARED_LIBS=ON \
      -DCMAKE_BUILD_TYPE=Release \
      -DENABLE_SHARED=TRUE \
      ..
  make all install
  cd ..
```

```
-- The C compiler identification is GNU 13.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/i686-w64-mingw32-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_BUILD_TYPE = Release
-- VERSION = 3.2.0, BUILD = 20260803
-- 32-bit build (i386)
-- CMAKE_INSTALL_PREFIX = /home/stian/SORT/opencubicplayer-code/i686-w64-mingw32-prefix
-- CMAKE_INSTALL_BINDIR = bin (/home/stian/SORT/opencubicplayer-code/i686-w64-mingw32-prefix/bin)
-- CMAKE_INSTALL_DATAROOTDIR = share (/home/stian/SORT/opencubicplayer-code/i686-w64-mingw32-prefix/share)
-- CMAKE_INSTALL_DOCDIR = share/doc/libjpeg-turbo (/home/stian/SORT/opencubicplayer-code/i686-w64-mingw32-prefix/share/doc/libjpeg-turbo)
-- CMAKE_INSTALL_INCLUDEDIR = include (/home/stian/SORT/opencubicplayer-code/i686-w64-mingw32-prefix/include)
-- CMAKE_INSTALL_LIBDIR = lib (/home/stian/SORT/opencubicplayer-code/i686-w64-mingw32-prefix/lib)
-- Shared libraries enabled (ENABLE_SHARED = 1)
-- Static libraries enabled (ENABLE_STATIC = 1)
-- Arithmetic decoding support enabled (WITH_ARITH_DEC = 1)
-- Arithmetic encoding support enabled (WITH_ARITH_ENC = 1)
-- TurboJPEG API library enabled (WITH_TURBOJPEG = 1)
-- TurboJPEG Java Native Access interfaces (TurboJPEG/JNA) disabled
   (WITH_JNA = )
-- Command-line tools enabled (WITH_TOOLS = 1)
-- Regression tests enabled (WITH_TESTS = 1)
-- Emulating libjpeg API/ABI v6.2 (WITH_JPEG7 = 0, WITH_JPEG8 = 0)
-- libjpeg API shared library version = 62.4.0
-- Compiler flags =  -O3 -DNDEBUG
-- Linker flags =
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Performing Test HAVE_BUILTIN_CTZL
-- Performing Test HAVE_BUILTIN_CTZL - Success
-- Performing Test INLINE_WORKS
-- Performing Test INLINE_WORKS - Success
-- INLINE = __inline__ __attribute__((always_inline)) (FORCE_INLINE = 1)
-- Performing Test HAVE_THREAD_LOCAL
-- Performing Test HAVE_THREAD_LOCAL - Success
-- THREAD_LOCAL = __thread
-- CMAKE_EXECUTABLE_SUFFIX = .exe
-- Looking for a ASM_NASM compiler
-- Looking for a ASM_NASM compiler - /usr/bin/nasm
-- The ASM_NASM compiler identification is NASM
-- Found assembler: /usr/bin/nasm
-- CMAKE_ASM_NASM_COMPILER = /usr/bin/nasm
-- CMAKE_ASM_NASM_OBJECT_FORMAT = win32
-- CMAKE_ASM_NASM_FLAGS =  -DWIN32
-- SIMD extensions: I386 (WITH_SIMD = 1)
-- System-supplied libspng disabled (WITH_SYSTEM_SPNG = 0)
-- System-supplied zlib disabled (WITH_SYSTEM_ZLIB = 0)
-- Looking for fmemopen
-- Looking for fmemopen - not found
-- FLOATTEST8 = sse
-- FLOATTEST12 =
-- Configuring done (1.7s)
-- Generating done (0.1s)
-- Build files have been written to: /home/stian/SORT/opencubicplayer-code/i686-w64-mingw32-src/libjpeg-turbo-3.2.0/build
[  0%] Building ASM_NASM object simd/CMakeFiles/simd.dir/i386/jsimdcpu.asm.obj
[  0%] Building ASM_NASM object simd/CMakeFiles/simd.dir/i386/jfdctflt-3dn.asm.obj
[  0%] Building ASM_NASM object simd/CMakeFiles/simd.dir/i386/jidctflt-3dn.asm.obj
[  1%] Building ASM_NASM object simd/CMakeFiles/simd.dir/i386/jquantf-3dn.asm.obj
[  1%] Building ASM_NASM object simd/CMakeFiles/simd.dir/i386/jccolor-mmx.asm.obj
[  1%] Building ASM_NASM object simd/CMakeFiles/simd.dir/i386/jcgray-mmx.asm.obj
[  1%] Building ASM_NASM object simd/CMakeFiles/simd.dir/i386/jcsample-mmx.asm.obj
[  1%] Building ASM_NASM object simd/CMakeFiles/simd.dir/i386/jdcolor-mmx.asm.obj
.....
[ 23%] Building C object CMakeFiles/jpeg-static.dir/src/jdarith.c.obj
[ 24%] Linking C static library libjpeg.a
[ 24%] Built target jpeg-static
[ 24%] Building C object src/spng/CMakeFiles/spng-static.dir/spng.c.obj
In file included from /usr/lib/gcc/i686-w64-mingw32/13-posix/include/immintrin.h:102,
                 from /home/stian/SORT/opencubicplayer-code/i686-w64-mingw32-src/libjpeg-turbo-3.2.0/src/spng/spng.c:6219:
/usr/lib/gcc/i686-w64-mingw32/13-posix/include/avx512fp16intrin.h:38:9: error: ‘_Float16’ is not supported on this target
   38 | typedef _Float16 __v8hf __attribute__ ((__vector_size__ (16)));
      |         ^~~~~~~~
/usr/lib/gcc/i686-w64-mingw32/13-posix/include/avx512fp16intrin.h:39:9: error: ‘_Float16’ is not supported on this target
   39 | typedef _Float16 __v16hf __attribute__ ((__vector_size__ (32)));
      |         ^~~~~~~~
/usr/lib/gcc/i686-w64-mingw32/13-posix/include/avx512fp16intrin.h:40:9: error: ‘_Float16’ is not supported on this target
   40 | typedef _Float16 __v32hf __attribute__ ((__vector_size__ (64)));
      |         ^~~~~~~~
/usr/lib/gcc/i686-w64-mingw32/13-posix/include/avx512fp16intrin.h:44:9: error: ‘_Float16’ is not supported on this target
   44 | typedef _Float16 __m128h __attribute__ ((__vector_size__ (16), __may_alias__));
      |         ^~~~~~~~
/usr/lib/gcc/i686-w64-mingw32/13-posix/include/avx512fp16intrin.h:45:9: error: ‘_Float16’ is not supported on this target
   45 | typedef _Float16 __m256h __attribute__ ((__vector_size__ (32), __may_alias__));
      |         ^~~~~~~~
/usr/lib/gcc/i686-w64-mingw32/13-posix/include/avx512fp16intrin.h:46:9: error: ‘_Float16’ is not supported on this target
   46 | typedef _Float16 __m512h __attribute__ ((__vector_size__ (64), __may_alias__));
      |         ^~~~~~~~
/usr/lib/gcc/i686-w64-mingw32/13-posix/include/avx512fp16intrin.h:49:9: error: ‘_Float16’ is not supported on this target
   49 | typedef _Float16 __m128h_u __attribute__ ((__vector_size__ (16),        \
      |         ^~~~~~~~
/usr/lib/gcc/i686-w64-mingw32/13-posix/include/avx512fp16intrin.h:51:9: error: ‘_Float16’ is not supported on this target
   51 | typedef _Float16 __m256h_u __attribute__ ((__vector_size__ (32),        \
      |         ^~~~~~~~
....
```

**Comment by dcommander** [comment]
Have you tried the latest code in the main branch? This may have already been fixed.

**Comment by mywave82** [comment]
I just tested b47f048e2387a31842e6c09b89d55a1772ed06c9, same issue

**Comment by mywave82** [comment]
It appears to fail from commit 54bd58cc306301892f1cdc2a00da64576ad1e232

**Comment by mywave82** [comment]
```
#ifndef SPNG_SSE
    #define SPNG_SSE 1
#endif

#if defined(__GNUC__) && !defined(__clang__)
    #if SPNG_SSE == 3
        #pragma GCC target("ssse3")
    #elif SPNG_SSE == 4
        #pragma GCC target("sse4.1")
    #else
        #pragma GCC target("sse2")
    #endif
#endif
```
This apparently does not fully work for mingw i686, it would probably compile if using   -msse2   compiler flags instead.

**Comment by mywave82** [comment]
This appear to be problem related to gcc 13, and fixed in gcc 14. Ubuntu mingw is still based on gcc 13.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109504

Work-around appears to be:
```C
#ifndef SPNG_SSE
    #define SPNG_SSE 1
#endif

#if defined(__GNUC__) && !defined(__clang__)
    #if SPNG_SSE == 3
        #pragma GCC target("ssse3")
    #elif SPNG_SSE == 4
        #pragma GCC target("sse4.1")
    #else
        #define __AVX512FP16INTRIN_H_INCLUDED     /* work-around for gcc i686 (mingw on Ubuntu) */
        #define __AVX512FP16VLINTRIN_H_INCLUDED   /* work-around for gcc i686 (mingw on Ubuntu) */
        #define _AVX512BF16VLINTRIN_H_INCLUDED    /* work-around for gcc i686 (mingw on Ubuntu) */
        #define _AVX512BF16INTRIN_H_INCLUDED      /* work-around for gcc i686 (mingw on Ubuntu) */
        #define _AVXNECONVERTINTRIN_H_INCLUDED    /* work-around for gcc i686 (mingw on Ubuntu) */
        #pragma GCC target("sse2")
    #endif
#endif
```

I can simply patch libjpeg-turbo in my mingw build-chain, since this is a gcc specific bug.

**Comment by dcommander** [comment]
I'll look into it in more detail.

**Comment by mywave82** [comment]
Reported to Ubuntu: https://bugs.launchpad.net/ubuntu/+source/gcc-mingw-w64/+bug/2162826

**Comment by dcommander** [comment]
Confirmed that `-msse2`, `-mssse3`, or `-msse4.1` work around the issue.  This highlights a deeper issue, however, which is that libspng isn't properly handling SIMD instruction targets.  It is trying to use SIMD intrinsics even if the target architecture doesn't support them, which is wrong.  Ugh.  All of the people who begged for PNG support, claiming it would be "a simple enhancement", can go stack rocks.

I think I can fix the libspng code by using preprocessor macros such as `__SSE2__`, etc.  I need to look at the same for Arm, since it is trying to use Neon instructions with Armv7 targets that might not support them.

**Comment by mywave82** [comment]
The compiler-failure is more or less a compiler-bug. But the lack of runtime-detection is not ideal.

**Comment by dcommander** [comment]
I would say it's more to the point that it's a compiler bug exposed by bad behavior on the part of libspng. That bad behavior could potentially expose other bugs, such as illegal instruction errors on older CPUs that lack SSE2 instructions.

**Comment by dcommander** [comment]
Try the latest code in main.  b9132f0ad099e06d951867e2b6f3d358eebc1f19 prevents SIMD instructions from being used with 32-bit x86 targets unless compile-time support for those instructions is explicitly enabled.  That should work around this issue as well.
