### ISSUE TITLE
Missing stddef.h include in jpeglib.h

### ISSUE THREAD

**Issue by kdschlosser** [libjpeg-turbo/libjpeg-turbo#766]
**Clear and concise description of the bug:**
when including `jpeglib.h` into a c source file when that source file is compiled it results in a compiler error.

```shell
libjpeg-turbo/jpeglib.h:841:3: error: unknown type name ‘size_t’
841 |   size_t free_in_buffer;        /* # of byte spaces remaining in buffer */
|   ^~~~~~
```

There is also the missing include of `stdio.h` as well.

```shell
libjpeg-turbo/jpeglib.h:970:52: error: unknown type name ‘FILE’
970 | EXTERN(void) jpeg_stdio_dest(j_compress_ptr cinfo, FILE *outfile);
|
```

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

in a c cource file simply include `jpeglib.h` and then compile

**Expected behavior:**
to be able to include jpeglib.h without any compiler errors

**Observed behavior:**

```shell
libjpeg-turbo/jpeglib.h:841:3: error: unknown type name ‘size_t’
841 |   size_t free_in_buffer;        /* # of byte spaces remaining in buffer */
|   ^~~~~~
```

```shell
libjpeg-turbo/jpeglib.h:970:52: error: unknown type name ‘FILE’
970 | EXTERN(void) jpeg_stdio_dest(j_compress_ptr cinfo, FILE *outfile);
|
```

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
gcc latest
Ubuntu 22.04

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
master branch

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

This behavior might be intentional as to allow the user to supply the types for those things. But then why would you use `size_t` and not `int`? and use `FILE` instead of `void *`. That is what doesn't make any sense. It looks like there is a specific use of the C stdlib and as such the proper includes need to be placed in the header file.

**Comment by dcommander** [comment]
Duplicate of #737, #116, and #17.  Please check existing issues before posting a new issue.  This is intended and [documented](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/be96fa0a403e5d084719757f7b8241d20393246d/libjpeg.txt#L896-L900) behavior of the libjpeg API.  That API predates ANSI/ISO C, and at the time the API was introduced (1991), not all compilers defined `FILE` and `size_t` in **stdio.h**.  Thus, the libjpeg API intentionally doesn't include **stdio.h** and leaves it up to the calling program to include it, if the calling program is using an ANSI compiler.  Even though libjpeg-turbo, unlike libjpeg, has never supported non-ANSI compilers, we would technically be breaking backward API compatibility if we included **stdio.h**.  My experience is that there are so many programs out there that use the libjpeg API (often in bizarre ways) that anything I change, no matter how minor, is going to break something somewhere.  (For example, I tried to get rid of the `JPP()`, `JMETHOD`, and `FAR` macros, which were only needed with non-ANSI compilers, but it broke some downstream builds.  I wouldn't doubt that there is some calling program out there that provides its own definition of `FILE` and `size_t` for some hackish purpose and relies on the fact that including **jpeglib.h** doesn't define those.)

**Comment by dcommander** [comment]
> I did search the issues. but perhaps because the issue is closed it didn't find it because I didn't search the closed issues. why would i search the closed issues when I am using the master/main branch when compiling. One would make the assumption that a closed issue is a fixed issue and because I was having the problem the issue was still present which would mean it is not fixed so the issue would be an open issue would it not?

Issues can be closed either as "completed" (fixed, resolved, integrated, implemented, etc.) or "not planned" (won't fix, duplicate, can't reproduce, etc.)  Of course it makes no sense to leave an issue open if it is not really a bug and thus there is no need to resolve it, or if it is a feature request that will not ever be implemented.  Doing so would needlessly clutter our issue tracker.  Our practices in this regard are the same as those of most OSS projects, and in most cases, the maintainers of those projects would not bother to have a conversation with you about this.

> The expectation of someone reading 839 lines of a text file for documentation and the text file name is not even something that would indicate it's documentation of any kind is a little bit looney tunes. Now if there was documentation that was compiled using doxygen which is easier to navigate and be able to locate this requirement you might have an argument. placing that information into a text file that has no indication of it being documentation and having the information on line 839.. come on now. We need to be a little realistic here. We know that NO ONE is going to read 3282 lines of a text file before trying to use this library,

Then you should build a time machine and forward your complaints to the 1990s, which is when said documentation was written (and not by me, to be clear.)  Rewriting all of that documentation using Doxygen would be a massive effort, and unless someone pays for my labor, why would I go to that trouble?  I'm not doing this for fun.  This is part of my job, and I barely have enough funding to maintain this project.  If you or someone else wants to go to the trouble of rewriting 33-year-old documentation using Doxygen, then make a pull request.  The TurboJPEG API is my creation, and it does have Doxygen documentation.  It also does not have the 33-year-old legacy of the libjpeg API to contend with.  Feel free to use that API if it is more to your liking.

> I still very much find it strange that there is the use of types that are not primitives. The types should be `unsigned long` or `int` for `size_t` and `void *` for `FILE`.

Again, forward your complaints to the 1990s.  Too much software relies on the legacy behavior to change it.

> To reduce the number of issues that get opened for this I suggest you add a comments in the `example.c` file explaining what the stdlib includes are for and that they are a requirement in order to compile. I also recommend updating the documentation so there is a stated requirement for those includes prior to including `jpeglib.h` or the user must define their own type for `FILE` and for `size_t`. This should be added right on the first page where it is easily seen and also in any build documentation as well.

It's a fallacy to assume that just because something is intuitive for you that it will be intuitive for everyone.  If I moved a piece of information to the head of a 33-year-old document every time someone complained about having to dig for the information, then the document would very soon become an unreadable mess (and the information that people requested to be at the head of the document would no longer be at the head of the document.)  The information in question has been in the same location since 1991.  libjpeg is a legacy API, so a lot of things about it will not be intuitive to someone who wasn't writing code in the early 90s.  I have done what I can to modernize it without breaking compatibility, but it largely is what it is at this point.  (You could always try to use libjpeg, which still supports MS-DOS and VAX systems even though this is 2024.)  libjpeg-turbo supports the libjpeg API for backward compatibility purposes, but you can find numerous issues and comments in which I discuss the need for a more modern replacement.  The TurboJPEG API is about halfway to becoming that, but it still lacks a lot of the features and flexibility of the libjpeg API.  Even if we fully replace the libjpeg API, a lot of legacy applications will still use the old API, and a lot of people who are familiar with libjpeg still expect the document to be in a text file, as it has been since 1991.  Again, if the newer TurboJPEG API is more to your liking, then feel free to use it.

> I am sure unless those changes are made I am not going to be the last person to open an issue for this, there is no information in either the provided example or in the build documentation about this requirement.

Oh, nos.  If I don't do exactly what you want, then pain and pestilence will befall me.  You think I haven't heard that before?    Go manage a project like this for 14 years before you presume to tell me how to do my job.

> As a note the example is also not going to work because of a missing include. `stddef.h` is needed for `exit` on a modern posix system compiling with gcc.

The example is compiled and tested as part of the default build, so obviously it does work.
